apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager-dev

resources:
  - ../../base
  - s3-pv-dev.yaml

# Удаляем базовый PV из генерации, чтобы не было конфликтов
patches:
  - target:
      kind: PersistentVolume
      name: s3-pv-placeholder
    patch: |-
      $patch: delete
  - patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: csi-s3-secret
      stringData:
        endpoint: "http://minio.messager-dev.svc.cluster.local:9000"