apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kiruganich/lab_k8s.git
    targetRevision: main
    path: k8s/overlays/dev  # ПРОВЕРЬ ЭТОТ ПУТЬ В ГИТЕ
  destination:
    server: https://kubernetes.default.svc
    namespace: messager-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kiruganich/lab_k8s.git
    targetRevision: main
    path: k8s/overlays/prod # ПРОВЕРЬ ЭТОТ ПУТЬ В ГИТЕ
  destination:
    server: https://kubernetes.default.svc
    namespace: messager-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true