apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: messager-prod

namePrefix: prod-

replicas:
- name: frontend
  count: 2
- name: bff
  count: 2
- name: user-service
  count: 2
- name: message-service
  count: 2

patches:
- path: patch-resources.yaml
- target:
    kind: Deployment
    name: message-service
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: uploads
        emptyDir: {}
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "host=prod-postgres user=messager password=messager dbname=messager_messages sslmode=disable"
- target:
    kind: Deployment
    name: user-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "host=prod-postgres user=messager password=messager dbname=messager_users sslmode=disable"
- target:
    kind: StorageClass
    name: csi-s3-minio
  patch: |-
    - op: replace
      path: /parameters/csi.storage.k8s.io~1provisioner-secret-namespace
      value: messager-prod
    - op: replace
      path: /parameters/csi.storage.k8s.io~1controller-publish-secret-namespace
      value: messager-prod
    - op: replace
      path: /parameters/csi.storage.k8s.io~1node-stage-secret-namespace
      value: messager-prod
    - op: replace
      path: /parameters/csi.storage.k8s.io~1node-publish-secret-namespace
      value: messager-prod
- target:
    kind: Secret
    name: csi-s3-secret
  patch: |-
    - op: replace
      path: /stringData/endpoint
      value: http://prod-minio.messager-prod.svc.cluster.local:9000

images:
- name: mablinov2704/frontend
  newTag: latest
- name: mablinov2704/bff
  newTag: latest
- name: mablinov2704/user-service
  newTag: latest
- name: mablinov2704/message-service
  newTag: latest