apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager-prod

resources:
  - ../../base
  - s3-pv-prod.yaml

commonLabels:
  environment: prod

images:
  - name: mablinov2704/frontend
    newTag: latest
  - name: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newTag: latest

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/affinity-patch.yaml
  - path: patches/ingress-host.yaml
  # Патч только на Secret
  - patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: csi-s3-secret
      stringData:
        endpoint: "http://minio.messager-prod.svc.cluster.local:9000"