apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager-prod
resources:
  - ../../base

patches:
  - path: patch-affinity.yaml
  - path: patch-resources.yaml

# Меняем NodePort для prod, чтобы не было конфликтов с dev
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: frontend
    spec:
      ports:
        - name: http
          nodePort: 30081