apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager-prod
resources:
  - ../../base
  - s3-storage.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        replicas: 3