apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-messager-uploads-prod
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - allow-delete
    - region=us-east-1
    - url=http://minio.messager-prod.svc.cluster.local:9000
    - use-path-request-style
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: messager-uploads-prod-handle
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: messager-prod
    volumeAttributes:
      bucketName: uploads
      mounter: rclone
      endpoint: http://minio.messager-prod.svc.cluster.local:9000