apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: messager
  labels:
    app: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: mablinov2704/bff:latest
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: messager-config
                  key: BFF_HTTP_PORT
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: messager-config
                  key: USER_SERVICE_URL
            - name: MSG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: messager-config
                  key: MSG_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: messager
spec:
  selector:
    app: bff
  ports:
    - name: http
      port: 8080
      targetPort: 8080