apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-placeholder
  labels:
    storage: s3-uploads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: placeholder