apiVersion: v1
kind: Secret
metadata:
  name: messager-secrets
type: Opaque
stringData:
  POSTGRES_USER: "messager"
  POSTGRES_PASSWORD: "messager"
  USER_DB_DSN: "host=postgres user=messager password=messager dbname=messager_users sslmode=disable"
  MSG_DB_DSN: "host=postgres user=messager password=messager dbname=messager_messages sslmode=disable"
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "password"